# shellcheck shell=bash
# Verification contracts, run finish/status/find, the fleet hub scaffold, and AGENTS.md export.
#
# Sourced by test/smoke.sh in order — sections share the demo-project state
# built by the ones before them. Helpers: test/lib.sh.
# shellcheck disable=SC2015  # `check && pass || fail` is the assertion idiom
# shellcheck disable=SC2154  # AOS/REPO/AOS_HOME and friends come from the driver

# --- verify: contracts ---
cat > "$AOS_HOME/projects/demo/policy.yaml" <<'EOF'
version: 1
plan_gate: auto
verification:
  adversarial_review: true
  contracts:
    - name: passing-check
      command: "true"
      required: true
    - name: failing-check
      command: "false"
      required: false
EOF
$AOS verify >/dev/null 2>&1 && pass "verify: required contract passes → exit 0" || fail "verify exit code"
grep -q "Verdict: PASS" "$RUN_DIR/verification.md" && pass "verification.md written" || fail "verification report"
grep -q '"name": "passing-check"' "$RUN_DIR/meta.json" && pass "verify: per-contract results recorded in meta" || fail "contract results not in meta"

# required failure → exit 1
cat > "$AOS_HOME/projects/demo/policy.yaml" <<'EOF'
version: 1
verification:
  contracts:
    - name: must-fail
      command: "false"
      required: true
EOF
if $AOS verify >/dev/null 2>&1; then fail "verify should exit 1 on required failure"; else pass "verify: required failure → exit 1"; fi

# zero contracts → nothing verified: exit 0, but the run's verdict must NOT flip to pass
cat > "$AOS_HOME/projects/demo/policy.yaml" <<'EOF'
version: 1
EOF
$AOS verify 2>/dev/null | grep -q "nothing was verified" && pass "verify: no contracts → says so" || fail "no-contract wording"
grep -q '"verification": "fail"' "$RUN_DIR/meta.json" && pass "verify: no contracts → no free pass recorded" || fail "zero-contract verify granted a pass"

# --- finish + status + find ---
review_active
$AOS run finish >/dev/null
$AOS status | grep -q "awaiting-review" && pass "status shows awaiting-review" || fail "status"
# the review action: a FINISHED run (no active pointer) must be closable via --run
RUN1_ID=$(basename "$RUN_DIR")
$AOS run state "done" --run "$RUN1_ID" | grep -q "→ done" && pass "run state --run closes a finished run" || fail "state --run failed"
$AOS run state awaiting-review --run "$RUN1_ID" >/dev/null   # restore for later console tests
$AOS run state "done" --run "no-such-run" 2>/dev/null && fail "state --run accepted unknown run" || pass "run state --run rejects unknown run"
$AOS find "LIN-1" | grep -q "ticket.md" && pass "find searches project memory" || fail "find"
$AOS find "LIN-1" --all | grep -q "■ demo" && pass "find --all sweeps projects (grouped)" || fail "find --all"

# --- fleet hub: default is scaffold-only (AOS never executes agents by default) ---
FLEET_OUT=$($AOS fleet)
echo "$FLEET_OUT" | grep -q "Fleet hub" || fail "fleet command failed"
echo "$FLEET_OUT" | grep -q "codex" && pass "fleet: prints the supported runtimes" || fail "runtime list missing"
grep -q "primary orchestration agent" "$AOS_HOME/fleet/AGENTS.md" && pass "fleet: AGENTS.md scaffolded" || fail "fleet AGENTS.md missing"
# shellcheck disable=SC2016  # literal backticks — matching the markdown code span, not expanding
grep -q '`demo`' "$AOS_HOME/fleet/AGENTS.md" && pass "fleet: routing table generated from registry" || fail "routing table missing"
grep -q "@AGENTS.md" "$AOS_HOME/fleet/CLAUDE.md" && pass "fleet: CLAUDE.md import shim" || fail "CLAUDE.md shim missing"
printf 'operator-tuned\n' > "$AOS_HOME/fleet/AGENTS.md"
$AOS fleet >/dev/null
grep -q "operator-tuned" "$AOS_HOME/fleet/AGENTS.md" && pass "fleet: re-run never overwrites a tuned hub" || fail "fleet clobbered AGENTS.md"
$AOS fleet --launch bogus 2>/dev/null && fail "fleet accepted unknown runtime" || pass "fleet: --launch rejects unknown runtime"
($AOS fleet --launch bogus 2>&1 || true) | grep -q "claude, codex, opencode, droid" && pass "fleet: --launch lists supported runtimes" || fail "supported list missing"

# --- export / context sync: context pack → per-agent files ---
$AOS export | grep -q "AGENTS.md" || fail "export did not report AGENTS.md"
grep -q "generated by \`aos\`" "$REPO/AGENTS.md" && pass "export: writes AGENTS.md with marker" || fail "AGENTS.md marker missing"
grep -q "Context pack" "$REPO/AGENTS.md" && pass "export: includes the context pack" || fail "pack content missing from AGENTS.md"
$AOS export >/dev/null && pass "export: re-export over own file works" || fail "re-export failed"
# a legacy-marker file (pre-multi-agent export) upgrades in place
printf '%s\n' '<!-- generated by `aos export` — do not edit by hand -->' 'old' > "$REPO/AGENTS.md"
$AOS export >/dev/null && grep -q 'generated by \`aos\`' "$REPO/AGENTS.md" \
  && pass "export: legacy-marker file upgraded in place" || fail "legacy marker not upgraded"
printf 'hand-written instructions\n' > "$REPO/AGENTS.md"
if $AOS export >/dev/null 2>&1; then fail "export overwrote a hand-written AGENTS.md"; else
  grep -q "hand-written" "$REPO/AGENTS.md" && pass "export: refuses to clobber a hand-written AGENTS.md" || fail "hand-written AGENTS.md was clobbered"
fi
rm "$REPO/AGENTS.md"

# --- context check/diff: drift detection is CI-gateable ---
# (demo project has codex+cursor+gemini registered by 190-agents later; here
# only claude is registered, so register codex for the file set first)
$AOS init --agent codex >/dev/null
$AOS context check | grep -q "current" && pass "context check: fresh files current" || fail "context check on fresh files"
printf '\n# local drift\n' >> "$REPO/AGENTS.md"
if $AOS context check >/dev/null 2>&1; then fail "context check passed on drifted file"; else pass "context check: drift → exit 1"; fi
$AOS context diff | grep -q '# local drift' && pass "context diff: shows the drift" || fail "diff did not show drift"
$AOS context sync >/dev/null && $AOS context check >/dev/null 2>&1 && pass "context sync: heals drift" || fail "sync did not heal"
rm "$REPO/AGENTS.md"

