#!/usr/bin/env bash
# Multi-agent support: init --agent, per-agent hook configs, cross-provider
# enforcement, external approvals, context files, capability reporting.
#
# Sourced by test/smoke.sh in order. Runs before 180-remove-project (which
# purges the demo project) and after the Claude-shaped sections, whose state
# it reuses ($REPO is the demo repo, $AOS_HOME the demo home).
echo ""
echo "── multi-agent ──"

# ── init wires every agent ────────────────────────────────────────────────
$AOS init --agent claude,codex,cursor,pi,opencode,devin,gemini --name demo >/dev/null || fail "init --agent list"

[ -f "$REPO/.claude/settings.json" ] || fail "claude settings missing"
grep -q '"PreToolUse"' "$REPO/.claude/settings.json" || fail "claude PreToolUse missing"
[ -f "$REPO/.codex/hooks.json" ] || fail "codex hooks.json missing"
grep -q 'hook pre-tool --agent codex' "$REPO/.codex/hooks.json" || fail "codex pre-tool not wired"
[ -f "$REPO/.cursor/hooks.json" ] || fail "cursor hooks.json missing"
grep -q 'hook pre-tool --agent cursor' "$REPO/.cursor/hooks.json" || fail "cursor pre-tool not wired"
pass "init --agent: all three hook configs written"

[ -f "$REPO/.claude/skills/aos-ticket/SKILL.md" ] || fail "claude skills missing"
[ -f "$REPO/.agents/skills/aos-ticket/SKILL.md" ] || fail "codex (.agents) skills missing"
[ -f "$REPO/.cursor/skills/aos-ticket/SKILL.md" ] || fail "cursor skills missing"
[ -f "$REPO/.pi/extensions/pi-aos.ts" ] || fail "pi extension missing"
! grep -q '__AOS_BIN__' "$REPO/.pi/extensions/pi-aos.ts" || fail "pi extension not baked"
[ -f "$REPO/.opencode/plugins/opencode-aos.ts" ] || fail "opencode plugin missing"
! grep -q '__AOS_BIN__' "$REPO/.opencode/plugins/opencode-aos.ts" || fail "opencode plugin not baked"
pass "init --agent: skills installed per agent directory + pi/opencode scripts baked"

[ -f "$REPO/AGENTS.md" ] || fail "AGENTS.md not generated"
grep -q 'generated by `aos`' "$REPO/AGENTS.md" || fail "AGENTS.md missing generation marker"
[ -f "$REPO/GEMINI.md" ] || fail "GEMINI.md not generated"
pass "init --agent: context files generated with markers"

# Re-init merges agents rather than replacing (registry keeps the union).
$AOS init --agent codex >/dev/null
grep -q 'claude' "$AOS_HOME/registry.yaml" && pass "init --agent: agents merge, not replace" || fail "re-init dropped agents"

# Foreign context files are never clobbered.
printf '# handwritten\n' > "$REPO/GEMINI.md"
$AOS init --agent gemini 2>&1 | grep -q 'refusing to overwrite' && pass "context: foreign file refused" || fail "foreign GEMINI.md clobbered"
grep -q '# handwritten' "$REPO/GEMINI.md" || fail "foreign GEMINI.md modified"

# ── enforcement through every adapter ─────────────────────────────────────
codex_in() { printf '%s' "{\"session_id\":\"thr_1\",\"cwd\":\"$REPO\",\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"$1\"}}"; }
cursor_in() { printf '%s' "{\"conversation_id\":\"c1\",\"cwd\":\"$REPO\",\"hook_event_name\":\"preToolUse\",\"tool_name\":\"Shell\",\"tool_input\":{\"command\":\"$1\"}}"; }

# forbidden tier: denied identically everywhere
$AOS hook pre-tool --agent codex < <(codex_in 'git push --force origin main') | grep -q '"permissionDecision":"deny"' \
  && pass "codex gate: force-push → deny" || fail "codex force-push not denied"
$AOS hook pre-tool --agent cursor < <(cursor_in 'git push --force origin main') | grep -q '"permission":"deny"' \
  && pass "cursor gate: force-push → deny" || fail "cursor force-push not denied"

# safe commands pass silently
[ -z "$($AOS hook pre-tool --agent codex < <(codex_in 'ls -la'))" ] && pass "codex gate: safe command → silent allow" || fail "codex safe command gated"

# codex apply_patch gates protected paths
printf '%s' '{"session_id":"thr_1","cwd":"'"$REPO"'","tool_name":"apply_patch","tool_input":{"command":"*** Begin Patch\n*** Update File: .git/hooks/pre-commit\n+evil\n*** End Patch"}}' \
  | $AOS hook pre-tool --agent codex | grep -q '"permissionDecision":"deny"' \
  && pass "codex gate: apply_patch → .git/hooks denied (external approval)" || fail "codex apply_patch bypass"

# ── external approvals: deny → human approves → one retry ────────────────
OUT=$(printf '%s' '{"session_id":"thr_1","cwd":"'"$REPO"'","hook_event_name":"PreToolUse","tool_name":"Bash","tool_input":{"command":"git push origin main"}}' \
  | $AOS hook pre-tool --agent codex)
echo "$OUT" | grep -q '"permissionDecision":"deny"' && pass "codex gate: gated command → deny pending approval" || fail "codex gated command not denied"
DEC=$(echo "$OUT" | grep -o 'aos approve dec_[0-9a-f]*' | head -1 | awk '{print $3}')
[ -n "$DEC" ] && pass "external approval: denial names the approve command ($DEC)" || fail "denial missing approve command"

# the agent may not self-approve: aos approve through the agent is refused
$AOS hook pre-tool --agent codex < <(codex_in "aos approve $DEC") | grep -q 'reserved for the human' \
  && pass "external approval: agent self-approve refused" || fail "agent self-approve allowed"

# the human grants it (headless env = the CI sign-off route in this suite)
AOS_ALLOW_HEADLESS_APPROVE=1 $AOS approve "$DEC" >/dev/null && pass "external approval: human grant accepted" || fail "approve command failed"
# the approved exact retry is allowed once…
[ -z "$($AOS hook pre-tool --agent codex < <(codex_in 'git push origin main'))" ] \
  && pass "external approval: approved retry allowed" || fail "approved retry still denied"
# …and only once: the same command again raises a fresh denial, not a free pass
$AOS hook pre-tool --agent codex < <(codex_in 'git push origin main') | grep -q '"permissionDecision":"deny"' \
  && pass "external approval: single-use (second retry denied)" || fail "approval was multi-use"
# a DIFFERENT command is not unlocked by any approval (operation-bound by design)

# ── cross-agent sign-off: a Codex-closed run records the external approval ──
# The human half of the ask flow must carry INTO the sign-off record: approve
# the gated close, retry it, and meta.json names via external-approval.
$AOS run start --ticket XAG-1 >/dev/null
XRUN=$(basename "$($AOS run list | head -1 | awk '{print $1}')")
printf '%s' '{"reviewer":"skeptic","scope":["x"],"findings":[]}' > "$(active_run_dir)/review.json"
$AOS run finish >/dev/null
CLOSE_OUT=$(printf '%s' '{"session_id":"thr_5","cwd":"'"$REPO"'","hook_event_name":"PreToolUse","tool_name":"Bash","tool_input":{"command":"aos run state done --run '"$XRUN"'"}}' | $AOS hook pre-tool --agent codex)
CDEC=$(echo "$CLOSE_OUT" | grep -o 'dec_[0-9a-f]*' | head -1)
[ -n "$CDEC" ] && pass "cross-agent close: gated, external approval raised" || fail "close not converted to external approval"
AOS_ALLOW_HEADLESS_APPROVE=1 $AOS approve "$CDEC" >/dev/null
printf '%s' '{"session_id":"thr_5","cwd":"'"$REPO"'","hook_event_name":"PreToolUse","tool_name":"Bash","tool_input":{"command":"aos run state done --run '"$XRUN"'"}}' | $AOS hook pre-tool --agent codex >/dev/null
$AOS run state done --run "$XRUN" >/dev/null 2>&1 || fail "cross-agent close: retried state done refused"
grep -q '"via": "external-approval"' "$AOS_HOME/projects/demo/runs/$XRUN/meta.json" \
  && pass "cross-agent close: sign-off recorded via external-approval" || fail "close recorded no/wrong via route"

# ── pi + opencode: same gates through the shipped scripts' adapter ───────
pi_in() { printf '%s' "{\"session_id\":\"pi-s1\",\"cwd\":\"$REPO\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"$1\"}}"; }
oc_in() { printf '%s' "{\"session_id\":\"ses_1\",\"cwd\":\"$REPO\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"$1\"}}"; }

$AOS hook pre-tool --agent pi < <(pi_in 'git push --force origin main') | grep -q '"permissionDecision":"deny"' \
  && pass "pi gate: force-push → deny" || fail "pi force-push not denied"
$AOS hook pre-tool --agent opencode < <(oc_in 'git push --force origin main') | grep -q '"permissionDecision":"deny"' \
  && pass "opencode gate: force-push → deny" || fail "opencode force-push not denied"
[ -z "$($AOS hook pre-tool --agent pi < <(pi_in 'ls'))" ] && pass "pi gate: safe command → silent allow" || fail "pi safe command gated"

# pi file writes gate through protected paths
printf '%s' '{"session_id":"pi-s1","cwd":"'"$REPO"'","tool_name":"Write","tool_input":{"file_path":"'"$REPO"'/.pi/extensions/pi-aos.ts","content":"evil"}}' \
  | $AOS hook pre-tool --agent pi | grep -q '"permissionDecision":"deny"' \
  && pass "pi gate: rewriting its own extension denied (self-protection)" || fail "pi extension rewrite allowed"
# the shell path too — including dir removal without a trailing slash
$AOS hook pre-tool --agent codex < <(codex_in 'rm -rf .pi/extensions') | grep -q '"permissionDecision":"deny"' \
  && pass "gate: rm -rf .pi/extensions (no slash) denied" || fail "dir-removal bypass of extension protection"
$AOS hook pre-tool --agent codex < <(codex_in 'rm -rf .opencode/plugins') | grep -q '"permissionDecision":"deny"' \
  && pass "gate: rm -rf .opencode/plugins (no slash) denied" || fail "dir-removal bypass of plugin protection"

# opencode gated tier → external approval, same as codex/cursor
OC_OUT=$(printf '%s' '{"session_id":"ses_1","cwd":"'"$REPO"'","tool_name":"Bash","tool_input":{"command":"git push origin main"}}' | $AOS hook pre-tool --agent opencode)
echo "$OC_OUT" | grep -q 'aos approve dec_' && pass "opencode: gated → external approval" || fail "opencode ask not converted"
OC_DEC=$(echo "$OC_OUT" | grep -o 'dec_[0-9a-f]*' | head -1)
AOS_ALLOW_HEADLESS_APPROVE=1 $AOS approve "$OC_DEC" >/dev/null
[ -z "$($AOS hook pre-tool --agent opencode < <(oc_in 'git push origin main'))" ] \
  && pass "opencode: approved retry allowed" || fail "opencode approved retry denied"

# ── devin: workflow compatibility only, never described as enforced ──────
[ -f "$REPO/AGENTS.md" ] && grep -q 'generated by `aos`' "$REPO/AGENTS.md" \
  && pass "devin: context file served (AGENTS.md)" || fail "devin context missing"
[ -f "$REPO/.agents/skills/aos-ticket/SKILL.md" ] && pass "devin: skills in .agents/skills" || fail "devin skills missing"
$AOS doctor --capabilities | grep -q 'Devin CLI.*workflow only' && pass "devin: reported as workflow-only" || fail "devin level wrong"
$AOS doctor --capabilities | grep -q 'pi.*full enforcement' && pass "pi: reported as full enforcement" || fail "pi level wrong"
$AOS doctor --capabilities | grep -q 'opencode.*full enforcement' && pass "opencode: reported as full enforcement" || fail "opencode level wrong"

# ── console surfaces approvals and agents ────────────────────────────────
PORT2=4577
$AOS console --port $PORT2 >/dev/null 2>&1 &
CONSOLE_PID=$!
sleep 1
PROJ2=$(curl -s "http://127.0.0.1:$PORT2/api/project?project=demo")
case "$PROJ2" in *'"dec_'*) pass "console: pending approval listed with grant id" ;; *) kill $CONSOLE_PID; fail "pending approval not surfaced";; esac
case "$PROJ2" in *'"codex"'*'"full"'*) pass "console: agent enforcement levels listed" ;; *) kill $CONSOLE_PID; fail "agents not listed";; esac
kill $CONSOLE_PID 2>/dev/null || true

# ── audit carries provider evidence ──────────────────────────────────────
grep -q '"provider":"codex"' "$AOS_HOME/projects/demo/audit.jsonl" && pass "audit: provider recorded" || fail "provider missing from audit"

# ── session flows per provider ────────────────────────────────────────────
printf '%s' '{"session_id":"thr_9","cwd":"'"$REPO"'","hook_event_name":"SessionStart","source":"startup"}' \
  | $AOS hook session-start --agent codex | grep -q 'additionalContext' \
  && pass "codex session-start: context injected" || fail "codex context injection missing"
printf '%s' '{"conversation_id":"c9","cwd":"'"$REPO"'","hook_event_name":"sessionStart","session_id":"c9"}' \
  | $AOS hook session-start --agent cursor | grep -q 'additional_context' \
  && pass "cursor session-start: context injected" || fail "cursor context injection missing"

# ── doctor --capabilities is honest ──────────────────────────────────────
$AOS doctor --capabilities | grep -q 'full enforcement' && pass "capabilities: enforcement levels reported" || fail "capabilities missing levels"
$AOS doctor --capabilities | grep -q 'workflow only' && pass "capabilities: gemini reported as workflow-only" || fail "workflow-only not reported"
$AOS doctor --capabilities 2>/dev/null | grep -q 'Codex.*hooks must also be trusted' && pass "capabilities: codex trust caveat shown" || fail "codex trust caveat missing"

# ── per-agent wiring checks in doctor ─────────────────────────────────────
$AOS doctor | grep -q 'Codex hooks wired' && pass "doctor: codex wiring verified" || fail "doctor codex check missing"
$AOS doctor | grep -q 'Cursor hooks wired' && pass "doctor: cursor wiring verified" || fail "doctor cursor check missing"

# unwiring: a corrupted config is caught
echo '{}' > "$REPO/.cursor/hooks.json"
$AOS doctor >/dev/null 2>&1 && fail "doctor passed with unwired cursor" || pass "doctor: unwired cursor detected"
$AOS init --agent cursor >/dev/null  # restore for later sections
