import fs from 'node:fs';
import path from 'node:path';
import { projectDir, readIfExists, tailLines, nowIso } from './paths.js';

// One canonical project memory (the AOS home), many generated context files.
// Providers that load a file at session start (Codex/AGENTS.md, Cursor via
// AGENTS.md, Gemini/GEMINI.md) get a derived copy; Claude gets native
// SessionStart injection and needs no file. Generated files carry a marker and
// are NEVER overwritten when a human wrote them.

export const CONTEXT_MARKER = '<!-- generated by `aos` — do not edit by hand. Source of truth: the AOS project home (aos context shows it). Re-run `aos context sync` after editing the memory. -->';
// The pre-multi-agent marker written by `aos export` — still ours, still
// upgradeable in place.
export const LEGACY_MARKER = '<!-- generated by `aos export` — do not edit by hand -->';

function isGeneratedFile(text) {
  return text.includes(CONTEXT_MARKER) || text.includes(LEGACY_MARKER);
}

// The rendered body shared by every generated file (same content export.js
// has always produced: pack + recent decisions + learnings).
export function renderAgentContext(projectId, projectName) {
  const dir = projectDir(projectId);
  const pack = readIfExists(path.join(dir, 'context', 'pack.md'));
  const decisions = readIfExists(path.join(dir, 'context', 'decisions.md'));
  const learnings = readIfExists(path.join(dir, 'learnings.md'));

  const parts = [
    CONTEXT_MARKER,
    `<!-- Edit the memory under ${dir}, not this file. Generated ${nowIso()}. -->`,
    '',
    `# ${projectName} — agent context`,
  ];
  if (pack) parts.push('', pack.trim());
  if (decisions) parts.push('', '## Recent decisions', '', tailLines(decisions, 40));
  if (learnings) parts.push('', '## Learnings', '', tailLines(learnings, 30));
  parts.push('');
  return parts.join('\n');
}

// Which file each agent reads. Agents whose contextFile is null get native
// injection (Claude) and no file is generated for them.
export function contextFilesFor(agents) {
  const files = new Set();
  for (const id of agents || []) {
    if (id === 'codex' || id === 'cursor') files.add('AGENTS.md');
    if (id === 'gemini') files.add('GEMINI.md');
  }
  return [...files];
}

// States a tracked file can be in:
//   current   generated by us and up to date
//   stale     generated by us, older than the memory (content differs)
//   foreign   exists but was NOT generated by us — never touched, reported
//   missing   tracked but not written yet
// The generated-at timestamp must not count as drift — normalize it out of
// comparisons or every check would report stale the moment after a sync.
function normalizeGenerated(text) {
  return String(text).replace(/Generated [^\n]*/g, 'Generated <ts>');
}

export function contextStatus(projectId, projectName, repoRoot, file) {
  const dest = path.join(repoRoot, file);
  const existing = readIfExists(dest);
  if (existing === null) return { file, state: 'missing' };
  if (!isGeneratedFile(existing)) return { file, state: 'foreign' };
  return normalizeGenerated(existing) === normalizeGenerated(renderAgentContext(projectId, projectName))
    ? { file, state: 'current' }
    : { file, state: 'stale' };
}

// Write one generated file. Refuses to touch foreign files; returns a report.
export function syncContextFile(projectId, projectName, repoRoot, file) {
  const status = contextStatus(projectId, projectName, repoRoot, file);
  if (status.state === 'foreign') {
    return {
      file,
      ok: false,
      error: `${file} already exists and looks hand-written — refusing to overwrite it. Merge its content into the AOS project memory (pack/decisions/learnings) or move the file aside, then re-run.`,
    };
  }
  fs.writeFileSync(path.join(repoRoot, file), renderAgentContext(projectId, projectName));
  return { file, ok: true, changed: status.state !== 'current' };
}

export function syncContextFiles(projectId, projectName, repoRoot, agents) {
  return contextFilesFor(agents).map((file) => syncContextFile(projectId, projectName, repoRoot, file));
}

// A short line-level diff for `aos context diff` — first differing hunk per
// file is plenty for a human deciding whether to sync.
export function diffContextFile(projectId, projectName, repoRoot, file, { maxLines = 40 } = {}) {
  const status = contextStatus(projectId, projectName, repoRoot, file);
  if (status.state === 'missing' || status.state === 'foreign') return { file, state: status.state, lines: [] };
  const oldLines = readIfExists(path.join(repoRoot, file)).split('\n');
  const newLines = renderAgentContext(projectId, projectName).split('\n');
  const lines = [];
  for (let i = 0; i < Math.max(oldLines.length, newLines.length) && lines.length < maxLines; i++) {
    if (oldLines[i] !== newLines[i]) {
      if (oldLines[i] !== undefined) lines.push(`- ${oldLines[i]}`);
      if (newLines[i] !== undefined) lines.push(`+ ${newLines[i]}`);
    }
  }
  return { file, state: status.state, lines };
}
