import fs from 'node:fs';
import path from 'node:path';
import { projectDir, readIfExists, tailLines, nowIso } from './paths.js';

const MARKER = '<!-- generated by `aos export` — do not edit by hand -->';

// Write the project's context as an AGENTS.md at the repo root, so runtimes
// that read AGENTS.md (Codex CLI, Cursor, Copilot — and Claude Code as a
// fallback) load the same context AOS injects via hooks. Context only: the
// gates and audit stay Claude Code-side.
export function exportAgentsMd(projectId, projectName, repoRoot) {
  const dir = projectDir(projectId);
  const pack = readIfExists(path.join(dir, 'context', 'pack.md'));
  const decisions = readIfExists(path.join(dir, 'context', 'decisions.md'));
  const learnings = readIfExists(path.join(dir, 'learnings.md'));

  const dest = path.join(repoRoot, 'AGENTS.md');
  const existing = readIfExists(dest);
  // Never clobber a hand-written AGENTS.md — only files we generated.
  if (existing !== null && !existing.includes(MARKER)) {
    throw new Error(
      `${dest} already exists and was not generated by aos — refusing to overwrite. Merge it into the context pack or move it aside first.`
    );
  }

  const parts = [
    MARKER,
    `<!-- Source of truth: ${dir} — edit there, then re-run \`aos export\`. Exported ${nowIso()}. -->`,
    '',
    `# ${projectName} — agent context`,
  ];
  if (pack) parts.push('', pack.trim());
  if (decisions) parts.push('', '## Recent decisions', '', tailLines(decisions, 40));
  if (learnings) parts.push('', '## Learnings', '', tailLines(learnings, 30));
  parts.push('');

  fs.writeFileSync(dest, parts.join('\n'));
  return dest;
}
