import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { test, before, after } from 'node:test';

let home, repo;
before(async () => {
  home = fs.mkdtempSync(path.join(os.tmpdir(), 'aos-ctx-'));
  repo = fs.mkdtempSync(path.join(os.tmpdir(), 'aos-repo-'));
  process.env.AOS_HOME = home;
  const { addProject } = await import('../../src/registry.js');
  addProject({ id: 'ctx', name: 'ctx', repo, agents: ['claude', 'codex', 'gemini'] });
  fs.mkdirSync(path.join(home, 'projects', 'ctx', 'context'), { recursive: true });
  fs.writeFileSync(path.join(home, 'projects', 'ctx', 'context', 'pack.md'), '# Context pack\n\nbody\n');
});
after(() => {
  fs.rmSync(home, { recursive: true, force: true });
  fs.rmSync(repo, { recursive: true, force: true });
  delete process.env.AOS_HOME;
});

const {
  syncContextFiles,
  contextStatus,
  contextFilesFor,
  diffContextFile,
  CONTEXT_MARKER,
} = await import('../../src/context-sync.js');

test('contextFilesFor maps agents to the files they read', () => {
  assert.deepEqual(contextFilesFor(['claude']), []); // native injection, no file
  assert.deepEqual(contextFilesFor(['codex', 'cursor']), ['AGENTS.md']); // one file, both agents
  assert.deepEqual(contextFilesFor(['gemini']), ['GEMINI.md']);
});

test('sync writes marked files; re-sync is a no-op state', () => {
  const reports = syncContextFiles('ctx', 'ctx', repo, ['codex', 'gemini']);
  assert.equal(reports.length, 2);
  assert.ok(reports.every((r) => r.ok && r.changed));
  const agents = fs.readFileSync(path.join(repo, 'AGENTS.md'), 'utf8');
  assert.ok(agents.includes(CONTEXT_MARKER));
  assert.ok(agents.includes('# ctx — agent context'));
  const again = syncContextFiles('ctx', 'ctx', repo, ['codex', 'gemini']);
  assert.ok(again.every((r) => r.ok && !r.changed));
  assert.equal(contextStatus('ctx', 'ctx', repo, 'AGENTS.md').state, 'current');
});

test('memory edits make the file stale; sync heals it', () => {
  fs.writeFileSync(path.join(home, 'projects', 'ctx', 'learnings.md'), '# Learnings\n- gotcha: x\n');
  assert.equal(contextStatus('ctx', 'ctx', repo, 'AGENTS.md').state, 'stale');
  const d = diffContextFile('ctx', 'ctx', repo, 'AGENTS.md');
  assert.ok(d.lines.some((l) => l.startsWith('+ ') && l.includes('gotcha')));
  syncContextFiles('ctx', 'ctx', repo, ['codex']);
  assert.equal(contextStatus('ctx', 'ctx', repo, 'AGENTS.md').state, 'current');
});

test('foreign files are refused, never clobbered', () => {
  fs.writeFileSync(path.join(repo, 'GEMINI.md'), '# our own rules\n');
  const report = syncContextFiles('ctx', 'ctx', repo, ['gemini'])[0];
  assert.equal(report.ok, false);
  assert.match(report.error, /hand-written/);
  assert.equal(fs.readFileSync(path.join(repo, 'GEMINI.md'), 'utf8'), '# our own rules\n');
  assert.equal(contextStatus('ctx', 'ctx', repo, 'GEMINI.md').state, 'foreign');
});

test('legacy-marker files (pre-multi-agent export) upgrade in place', () => {
  fs.writeFileSync(
    path.join(repo, 'AGENTS.md'),
    '<!-- generated by `aos export` — do not edit by hand -->\nold\n'
  );
  const report = syncContextFiles('ctx', 'ctx', repo, ['codex'])[0];
  assert.equal(report.ok, true);
  assert.ok(fs.readFileSync(path.join(repo, 'AGENTS.md'), 'utf8').includes(CONTEXT_MARKER));
});
